# Generated by Django 5.2.17 on 2026-08-15 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='speaker name')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='speaker title')),
                ('quote_text', models.TextField()),
                ('source', models.CharField(blank=True, help_text='Where/when it was said, e.g. "Press conference in Baku" or "Truth Social post".', max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='quotes/')),
                ('quote_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('related_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='news.article')),
            ],
            options={
                'ordering': ['-quote_date', '-id'],
            },
        ),
    ]
