# Generated by Django 5.2.17 on 2026-08-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, upload_to='authors/'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, upload_to='quotes/'),
        ),
    ]
