# Generated by Django 5.2.17 on 2026-08-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_image_alter_author_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show_author_name',
            field=models.BooleanField(default=True, help_text='Uncheck to display "Editorial" instead of the author\'s name on this article.'),
        ),
    ]
