# Generated by Django 5.2.17 on 2026-08-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_create_admin_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='author',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='author',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='author',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='author',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order on the About page.'),
        ),
        migrations.AddField(
            model_name='author',
            name='other_social_url',
            field=models.URLField(blank=True, verbose_name='Other'),
        ),
        migrations.AddField(
            model_name='author',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='author',
            name='show_on_about',
            field=models.BooleanField(default=False, help_text='Show this person as a card on the public About page, with their own profile page.'),
        ),
        migrations.AddField(
            model_name='author',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='author',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='author',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='X (Twitter)'),
        ),
        migrations.AddField(
            model_name='author',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='article',
            name='show_author_name',
            field=models.BooleanField(default=True, help_text='Uncheck to display "News Desk" instead of the author\'s name on this article.'),
        ),
    ]
