# Generated by Django 5.2.17 on 2026-08-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_author_options_author_bio_author_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='co_authors',
            field=models.ManyToManyField(blank=True, related_name='co_authored_articles', to='news.author'),
        ),
    ]
