# Generated by Django 5.2.17 on 2026-08-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_article_co_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_credit',
            field=models.CharField(blank=True, help_text='Optional — e.g. "Photo: Reuters" or "AI-generated image". Shown under the main image.', max_length=255),
        ),
    ]
