# Generated by Django 5.2.17 on 2026-08-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_article_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_reference',
            field=models.BooleanField(default=False, help_text='Featured in the "Referenced by" widget beside the homepage header (newest 6, shown with a circular thumbnail).', verbose_name='reference article'),
        ),
    ]
