# Generated by Django 5.2.17 on 2026-08-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_article_is_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='youtube_id',
        ),
    ]
