# Generated by Django 5.2.17 on 2026-08-25 17:12

from django.db import migrations, models


def seed_homepage_order(apps, schema_editor):
    # Start homepage_order from each category's existing nav `order` so the
    # first deploy of this feature doesn't leave every category tied at 0
    # (arbitrary DB-order pairing) — admins can freely rearrange from there.
    Category = apps.get_model('news', 'Category')
    for category in Category.objects.order_by('order', 'name'):
        category.homepage_order = category.order
        category.save(update_fields=['homepage_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_remove_article_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='homepage_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='show_on_homepage',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(seed_homepage_order, migrations.RunPython.noop),
    ]
