# Generated by Django 5.2.17 on 2026-08-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_category_homepage_order_category_show_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='homepage_new_row',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='homepage_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
