# Generated by Django 5.2.17 on 2026-08-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_category_homepage_new_row_category_homepage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Eligible for the homepage hero + "More Headlines" row (newest 5 shown). Unflagged articles never appear there, no matter how recent.'),
        ),
    ]
