# Generated by Django 5.2.17 on 2026-09-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_article_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='homepage_zone',
            field=models.CharField(choices=[('top', "Top (before Editor's Picks)"), ('after_editors_picks', "After Editor's Picks"), ('row1', 'Full-width row (before Did You Know?)'), ('row2', 'Full-width row (after Did You Know?)'), ('bottom', 'Bottom (after Follow)'), ('with_climate', 'Paired with Climate (page end)')], default='top', max_length=30),
        ),
    ]
