# Generated by Django 5.2.17 on 2026-08-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ads_txt_content',
            field=models.TextField(blank=True, help_text='Leave blank to auto-generate from the Publisher ID above. Only fill this in if Google gives you different/additional lines.', verbose_name='ads.txt override'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adsense_publisher_id',
            field=models.CharField(blank=True, help_text='e.g. pub-1234567890123456. Enables the site-wide AdSense auto-ads script and generates ads.txt automatically.', max_length=20, verbose_name='Google AdSense Publisher ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ga_measurement_id',
            field=models.CharField(blank=True, help_text='e.g. G-XXXXXXXXXX. Leave blank to disable Analytics entirely.', max_length=20, verbose_name='Google Analytics Measurement ID'),
        ),
    ]
