# Generated by Django 5.2.17 on 2026-08-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mediafolder_mediaasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal label only — never shown publicly.', max_length=150)),
                ('zone', models.CharField(choices=[('leaderboard', 'Leaderboard 970×90 (homepage top & footer)'), ('sidebar', 'Sidebar 300×600 (article/category/tag/search/team pages)')], max_length=20)),
                ('image', models.ImageField(upload_to='ads/')),
                ('link_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, help_text='Leave blank to start immediately.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Leave blank to run indefinitely.', null=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
