# Generated by Django 5.2.17 on 2026-08-20 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_advertisement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
