# Generated by Django 5.2.17 on 2026-08-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_facebook_url_sitesettings_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Unchecked pages 404 on the site and drop out of the footer, without deleting the row.'),
        ),
    ]
