# Generated by Django 5.2.17 on 2026-08-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_description',
            field=models.CharField(blank=True, help_text="Fallback <meta description> and social-share text for pages that don't set their own (homepage, category pages, ...). A generic sentence is used if left blank.", max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_share_image',
            field=models.ImageField(blank=True, help_text='Fallback image for social share previews (Facebook/X/...) on pages without their own image, like the homepage.', upload_to='site/', verbose_name='Default social share image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_site_verification',
            field=models.CharField(blank=True, help_text='Paste just the content value from Search Console\'s HTML tag verification method, e.g. "abcXYZ123...". Leave blank if unused.', max_length=100, verbose_name='Google Search Console verification'),
        ),
    ]
