# Generated by Django 5.2.17 on 2026-08-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_default_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_meta_title',
            field=models.CharField(blank=True, help_text="Overrides the homepage's <title> tag (browser tab + Google's search result headline) only — every other page keeps its own. Leave blank to use the default site name + tagline.", max_length=150, verbose_name='Homepage SEO title'),
        ),
    ]
